### ISSUE TITLE
console,新增注册中心， 没有连接成功，后台一直报错，然后删除。 但是后台还是一直报错。

### ISSUE THREAD

**Issue by tsw424** [dangdangdotcom/elastic-job#115]
删除后，应该结束此注册中心的 试探拦截。 失败了就结束了。 别再后台老重试了。我都删除了，后台就没必要连接了。 

] 2016-06-22 18:35:48,282 --http-bio-8080-exec-9-SendThread(192.168.10.163:2128)-- [org.apache.zookeeper.ClientCnxn] Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect 
java.net.ConnectException: Connection refused: no further information
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_45]
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_45]
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
[WARN ] 2016-06-22 18:35:48,446 --http-bio-8080-exec-3-SendThread(192.168.10.163:2128)-- [org.apache.zookeeper.ClientCnxn] Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect 
java.net.ConnectException: Connection refused: no further information
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_45]
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_45]
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
[INFO ] 2016-06-22 18:35:49,383 --http-bio-8080-exec-9-SendThread(192.168.10.163:2128)-- [org.apache.zookeeper.ClientCnxn] Opening socket connection to server 192.168.10.163/192.168.10.163:2128. Will not attempt to authenticate using SASL (unknown error) 
[INFO ] 2016-06-22 18:35:49,550 --http-bio-8080-exec-3-SendThread(192.168.10.163:2128)-- [org.apache.zookeeper.ClientCnxn] Opening socket connection to server 192.168.10.163/192.168.10.163:2128. Will not attempt to authenticate using SASL (unknown error) 
[WARN ] 20

**Comment by haocao** [comment]
Fixed in 2.0.1

**Comment by terrymanu** [comment]
这个问题并没有解决，根源是注册中心连不上时，curator会反复重试。
