### ISSUE TITLE
job抛出运行时异常后，后续不会继续触发

### ISSUE THREAD

**Issue by kris1985** [dangdangdotcom/elastic-job#13]
job抛出运行时异常后，后续不会继续触发。相当于任务停止。

在job中添加try catch 可以解决此问题。

**Comment by haocao** [comment]
经过测试可以调度，还请详细测试场景或日志。以下是测试日志：
------ OneOffElasticDemoJob process: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] at 2015-10-19 17:14:45 ------
[ERROR] 2015-10-19 17:14:45,179 --DEFAULT.oneOffElasticJob_Scheduler_Worker-1-- [org.quartz.core.JobRunShell] Job DEFAULT.oneOffElasticJob threw an unhandled Exception:  
java.lang.RuntimeException: null
	at com.dangdang.example.elasticjob.fixture.repository.FooRepository.setInactive(FooRepository.java:66) ~[classes/:na]
	at com.dangdang.example.elasticjob.spring.job.OneOffElasticDemoJob.process(OneOffElasticDemoJob.java:44) ~[classes/:na]
	at com.dangdang.ddframe.job.api.AbstractOneOffElasticJob.executeJob(AbstractOneOffElasticJob.java:29) ~[classes/:na]
	at com.dangdang.ddframe.job.api.AbstractElasticJob.executeJobInternal(AbstractElasticJob.java:98) ~[classes/:na]
	at com.dangdang.ddframe.job.api.AbstractElasticJob.execute(AbstractElasticJob.java:78) ~[classes/:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.1.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.1.jar:na]
[ERROR] 2015-10-19 17:14:45,179 --DEFAULT.oneOffElasticJob_Scheduler_Worker-1-- [org.quartz.core.ErrorLogger] Job (DEFAULT.oneOffElasticJob threw an exception. 
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) ~[quartz-2.2.1.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.1.jar:na]
Caused by: java.lang.RuntimeException: null
	at com.dangdang.example.elasticjob.fixture.repository.FooRepository.setInactive(FooRepository.java:66) ~[classes/:na]
	at com.dangdang.example.elasticjob.spring.job.OneOffElasticDemoJob.process(OneOffElasticDemoJob.java:44) ~[classes/:na]
	at com.dangdang.ddframe.job.api.AbstractOneOffElasticJob.executeJob(AbstractOneOffElasticJob.java:29) ~[classes/:na]
	at com.dangdang.ddframe.job.api.AbstractElasticJob.executeJobInternal(AbstractElasticJob.java:98) ~[classes/:na]
	at com.dangdang.ddframe.job.api.AbstractElasticJob.execute(AbstractElasticJob.java:78) ~[classes/:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.1.jar:na]
	... 1 common frames omitted
------ OneOffElasticDemoJob process: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] at 2015-10-19 17:14:50 ------
[ERROR] 2015-10-19 17:14:50,019 --DEFAULT.oneOffElasticJob_Scheduler_Worker-1-- [org.quartz.core.JobRunShell] Job DEFAULT.oneOffElasticJob threw an unhandled Exception:  
java.lang.RuntimeException: null
	at com.dangdang.example.elasticjob.fixture.repository.FooRepository.setInactive(FooRepository.java:66) ~[classes/:na]
	at com.dangdang.example.elasticjob.spring.job.OneOffElasticDemoJob.process(OneOffElasticDemoJob.java:44) ~[classes/:na]
	at com.dangdang.ddframe.job.api.AbstractOneOffElasticJob.executeJob(AbstractOneOffElasticJob.java:29) ~[classes/:na]
	at com.dangdang.ddframe.job.api.AbstractElasticJob.executeJobInternal(AbstractElasticJob.java:98) ~[classes/:na]
	at com.dangdang.ddframe.job.api.AbstractElasticJob.execute(AbstractElasticJob.java:78) ~[classes/:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.1.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.1.jar:na]
[ERROR] 2015-10-19 17:14:50,019 --DEFAULT.oneOffElasticJob_Scheduler_Worker-1-- [org.quartz.core.ErrorLogger] Job (DEFAULT.oneOffElasticJob threw an exception. 
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) ~[quartz-2.2.1.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.1.jar:na]
Caused by: java.lang.RuntimeException: null
	at com.dangdang.example.elasticjob.fixture.repository.FooRepository.setInactive(FooRepository.java:66) ~[classes/:na]
	at com.dangdang.example.elasticjob.spring.job.OneOffElasticDemoJob.process(OneOffElasticDemoJob.java:44) ~[classes/:na]
	at com.dangdang.ddframe.job.api.AbstractOneOffElasticJob.executeJob(AbstractOneOffElasticJob.java:29) ~[classes/:na]
	at com.dangdang.ddframe.job.api.AbstractElasticJob.executeJobInternal(AbstractElasticJob.java:98) ~[classes/:na]
	at com.dangdang.ddframe.job.api.AbstractElasticJob.execute(AbstractElasticJob.java:78) ~[classes/:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.1.jar:na]
	... 1 common frames omitted
