### ISSUE TITLE
Java方式启动，jobName使用中文名称，script类型的job会报cron表达式错误，实际上cron表达式是正确的

### ISSUE THREAD

**Issue by workcheng** [dangdangdotcom/elastic-job#134]
报错信息：
15:19:34.410 [main] ERROR o.a.z.server.NIOServerCnxnFactory - Thread Thread[main,5,main] died
java.lang.RuntimeException: CronExpression '0/5' is invalid.
	at org.quartz.CronScheduleBuilder.cronSchedule(CronScheduleBuilder.java:111) ~[quartz-2.2.1.jar:na]
	at com.dangdang.ddframe.job.lite.internal.schedule.JobScheduleController.createTrigger(JobScheduleController.java:83) ~[elastic-job-lite-core-2.0.0-SNAPSHOT.jar:na]
	at com.dangdang.ddframe.job.lite.internal.schedule.JobScheduleController.scheduleJob(JobScheduleController.java:58) ~[elastic-job-lite-core-2.0.0-SNAPSHOT.jar:na]
	at com.dangdang.ddframe.job.lite.api.JobScheduler.init(JobScheduler.java:90) ~[elastic-job-lite-core-2.0.0-SNAPSHOT.jar:na]
	at com.cheng.test.JavaLiteJobMain.setUpScriptJob(JavaLiteJobMain.java:95) ~[test-classes/:na]
	at com.cheng.test.JavaLiteJobMain.main(JavaLiteJobMain.java:63) ~[test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) ~[idea_rt.jar:na]
Caused by: java.text.ParseException: Unexpected end of expression.
	at org.quartz.CronExpression.buildExpression(CronExpression.java:494) ~[quartz-2.2.1.jar:na]
	at org.quartz.CronExpression.<init>(CronExpression.java:276) ~[quartz-2.2.1.jar:na]
	at org.quartz.CronScheduleBuilder.cronSchedule(CronScheduleBuilder.java:107) ~[quartz-2.2.1.jar:na]
	... 10 common frames omitted

执行的代码：
private static void setUpScriptJob(final CoordinatorRegistryCenter regCenter) throws IOException {
        String cron = "0/5 * * * * ?";
        JobCoreConfiguration coreConfig = JobCoreConfiguration.newBuilder("测试scriptElasticJob", cron, 3).jobEventConfiguration(getJobEventConfigurations()).build();
        ScriptJobConfiguration scriptJobConfig = new ScriptJobConfiguration(coreConfig, buildScriptCommandLine());
        new JobScheduler(regCenter, LiteJobConfiguration.newBuilder(scriptJobConfig).build()).init();
    }

**Comment by terrymanu** [comment]
您的报错信息的cron表达式是 '0/5'并不正确，和贴出来的代码不符。请认真阅读文档和代码，elastic-job目前已经不会在出现显著的不能运行的bug。谢谢合作。

**Comment by workcheng** [comment]
这么一说，我刚刚又测试了一下，这个bug报的真的很奇葩，我把zookeeper的这个节点的job的整个配置删除掉了，然后在运行就可以了，应该是之前运行的时候，这个错误的cron表达式配置传上去了，之后再继续运行没有覆盖之前那个配置导致的
