### ISSUE TITLE
2.0.1版本elastic-job-example-lite项目下JavaLiteJobMain 无法启动

### ISSUE THREAD

**Issue by wenlizhao** [dangdangdotcom/elastic-job#166]
当前环境eclipse 下 第一次构建项目可以正常启动，clean后在编译 无法启动报错如下：
[ERROR] 2016-11-14 19:09:05,006 --main-- [org.apache.zookeeper.server.NIOServerCnxnFactory] Thread Thread[main,5,main] died 
java.lang.Error: Unresolved compilation problem: 
	The constructor LiteJobConfiguration.Builder(JobTypeConfiguration) is undefined

	at com.dangdang.ddframe.job.lite.config.LiteJobConfiguration.newBuilder(LiteJobConfiguration.java:76) ~[classes/:na]
	at com.dangdang.ddframe.job.example.JavaLiteJobMain.setUpDataflowJob(JavaLiteJobMain.java:94) ~[classes/:na]
	at com.dangdang.ddframe.job.example.JavaLiteJobMain.main(JavaLiteJobMain.java:68) ~[classes/:na]

**Comment by terrymanu** [comment]
为了避免混淆和误导，如果自己关闭的issue请说明原因。
