### ISSUE TITLE
disconf和elastic-job同时使用启动disconf出现错误：cannot get watch module java.lang.Exception: cannot get: RemoteUrl [url=/api/zoo/hosts, serverList=[xxxx], urls=[http://xxxxx/api/zoo/hosts]]

### ISSUE THREAD

**Issue by jxctx88** [dangdangdotcom/elastic-job#173]
`localhost-startStop-1] [ERROR] [c.b.d.client.watch.WatchFactory:59  ] - cannot get watch module
java.lang.Exception: cannot get: RemoteUrl [url=/api/zoo/hosts, serverList=[xxxxxx:8081], urls=[http://xxxx:8081/api/zoo/hosts]]
	at com.baidu.disconf.core.common.restful.impl.RestfulMgrImpl.getJsonData(RestfulMgrImpl.java:109) ~[disconf-core-2.6.30.jar:na]
	at com.baidu.disconf.client.fetcher.impl.FetcherMgrImpl.getValueFromServer(FetcherMgrImpl.java:70) ~[disconf-client-2.6.30.jar:na]
	at com.baidu.disconf.client.watch.WatchFactory.getWatchMgr(WatchFactory.java:43) ~[disconf-client-2.6.30.jar:na]
	at com.baidu.disconf.client.core.DisconfCoreFactory.getDisconfCoreMgr(DisconfCoreFactory.java:32) [disconf-client-2.6.30.jar:na]
	at com.baidu.disconf.client.DisconfMgr.firstScan(DisconfMgr.java:96) [disconf-client-2.6.30.jar:na]
	at com.baidu.disconf.client.DisconfMgrBean.postProcessBeanDefinitionRegistry(DisconfMgrBean.java:75) [disconf-client-2.6.30.jar:na]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) [spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) [spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:674) [spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:519) [spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446) [spring-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328) [spring-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) [spring-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973) [catalina.jar:7.0.52]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467) [catalina.jar:7.0.52]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.52]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [catalina.jar:7.0.52]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [catalina.jar:7.0.52]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632) [catalina.jar:7.0.52]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1229) [catalina.jar:7.0.52]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875) [catalina.jar:7.0.52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]`

**Comment by jxctx88** [comment]
disconf使用的是2.6.30的版本，elastic-job使用的是2.0.1的版本
使用下面的配置解决问题
<dependency>
            <groupId>com.baidu.disconf</groupId>
            <artifactId>disconf-client</artifactId>
            <exclusions>
	             <exclusion>
		          <artifactId>gson</artifactId>
		          <groupId>com.google.code.gson</groupId>
		        </exclusion>
	        </exclusions>
        </dependency>

<dependency>
            <groupId>com.dangdang</groupId>
            <artifactId>elastic-job-lite-core</artifactId>
            <exclusions>
		        <exclusion>
		        	 <groupId>org.eclipse.jetty.aggregate</groupId>
                	<artifactId>jetty-all-server</artifactId>
		        </exclusion>
      		</exclusions>
        </dependency>

**Comment by haocao** [comment]
项目依赖中的版本冲突是比较常见的问题，我们也在调整ejb的相关依赖，尽量做到依赖最小化。
