### ISSUE TITLE
[question or bug]203版本的lite example跑不起来

### ISSUE THREAD

**Issue by jinleileiking** [dangdangdotcom/elastic-job#201]
用curator的test server跑 lite example, crash

```
java -cp elastic-job-example-lite-java-2.0.3.jar:/home/xxxx/.m2/repository/com/dangdang/elastic-job-common-core/2.0.3/elastic-job-common-core-2.0.3.jar:/home/xxxx/tools/elastic-job/elastic-job-example/elastic-job-example-embed-zk/target/elastic-job-example-embed-zk-2.0.3.jar:/home/xx/.m2/repository/org/apache/curator/curator-test/2.10.0/curator-test-2.10.0.jar:    com.dangdang.ddframe.job.example.JavaMain
Exception in thread "main" java.lang.NoClassDefFoundError: javassist/NotFoundException
        at org.apache.curator.test.TestingServer.<clinit>(TestingServer.java:33)
        at com.dangdang.ddframe.job.example.EmbedZookeeperServer.start(EmbedZookeeperServer.java:43)
        at com.dangdang.ddframe.job.example.JavaMain.main(JavaMain.java:67)
Caused by: java.lang.ClassNotFoundException: javassist.NotFoundException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
Exception in thread "Thread-0" java.lang.NullPointerException
        at com.dangdang.ddframe.job.example.EmbedZookeeperServer$1.run(EmbedZookeeperServer.java:55)

```

怀疑是curator版本不对导致，我mvn package的curator版本是 2.10，是不是要指定依赖的curator版本？

**Comment by terrymanu** [comment]
是否是本地exclude了javassist导致。环境问题请自行解决
