### ISSUE TITLE
Lite 版本遇到了有分片触发不了，没有按时执行

### ISSUE THREAD

**Issue by Ah39** [dangdangdotcom/elastic-job#324]
0x0000000086619140 这个地址，好像是死锁，把Curator-TreeCache的线程block住了

"Curator-TreeCache-46" daemon prio=10 tid=0x00007fa25005a000 nid=0x3f22 waiting for monitor entry [0x00007fa349fde000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.quartz.simpl.RAMJobStore.pauseAll(RAMJobStore.java:1307)
	- waiting to lock <0x0000000086619140> (a java.lang.Object)
	at org.quartz.core.QuartzScheduler.pauseAll(QuartzScheduler.java:1412)
	at org.quartz.impl.StdScheduler.pauseAll(StdScheduler.java:433)
	at com.dangdang.ddframe.job.lite.internal.schedule.JobScheduleController.pauseJob(JobScheduleController.java:127)
	at com.dangdang.ddframe.job.lite.internal.server.JobOperationListenerManager$JobPausedStatusJobListener.dataChanged(JobOperationListenerManager.java:114)
	at com.dangdang.ddframe.job.lite.internal.listener.AbstractJobListener.childEvent(AbstractJobListener.java:37)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:732)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:726)
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85)
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:725)
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:71)
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:843)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x000000008664d330> (a java.util.concurrent.ThreadPoolExecutor$Worker)
    
    
"ENV_Online_**********************_QuartzSchedulerThread" prio=10 tid=0x00007fa38cff8000 nid=0x3f28 in Object.wait() [0x00007fa349bda000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:503)
	at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1342)
	- locked <0x0000000584216c40> (a org.apache.zookeeper.ClientCnxn$Packet)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1040)
	at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:226)
	at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:215)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForegroundStandard(ExistsBuilderImpl.java:212)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:205)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:168)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:39)
	at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.isExisted(ZookeeperRegistryCenter.java:210)
	at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.isJobRootNodeExisted(JobNodeStorage.java:109)
	at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.createJobNodeIfNeeded(JobNodeStorage.java:103)
	at com.dangdang.ddframe.job.lite.internal.execution.ExecutionService.setMisfire(ExecutionService.java:189)
	at com.dangdang.ddframe.job.lite.internal.schedule.JobTriggerListener.triggerMisfired(JobTriggerListener.java:47)
	at org.quartz.core.QuartzScheduler.notifyTriggerListenersMisfired(QuartzScheduler.java:1905)
	at org.quartz.core.SchedulerSignalerImpl.notifyTriggerListenersMisfired(SchedulerSignalerImpl.java:74)
	at org.quartz.simpl.RAMJobStore.applyMisfire(RAMJobStore.java:1354)
	at org.quartz.simpl.RAMJobStore.acquireNextTriggers(RAMJobStore.java:1412)
	- locked <0x0000000086619140> (a java.lang.Object)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)

   Locked ownable synchronizers:
	- None

**Comment by terrymanu** [comment]
请参照提issue的模板提交，这种issue我们无法定位和重现
