### ISSUE TITLE
2.0.5 Lite 版本遇到了有分片触发不了，没有按时执行 

### ISSUE THREAD

**Issue by Ah39** [dangdangdotcom/elastic-job#325]
0x0000000086619140 这个地址，好像是死锁，把Curator-TreeCache的线程block住了
任务misfire后，再次触发,从jstack信息来看。
ps：要是能快速重现，我自己就解决了，还浪费时间在这里提issues

"Curator-TreeCache-46" daemon prio=10 tid=0x00007fa25005a000 nid=0x3f22 waiting for monitor entry [0x00007fa349fde000]
java.lang.Thread.State: BLOCKED (on object monitor)
at org.quartz.simpl.RAMJobStore.pauseAll(RAMJobStore.java:1307)
- waiting to lock <0x0000000086619140> (a java.lang.Object)
at org.quartz.core.QuartzScheduler.pauseAll(QuartzScheduler.java:1412)
at org.quartz.impl.StdScheduler.pauseAll(StdScheduler.java:433)
at com.dangdang.ddframe.job.lite.internal.schedule.JobScheduleController.pauseJob(JobScheduleController.java:127)
at com.dangdang.ddframe.job.lite.internal.server.JobOperationListenerManager$JobPausedStatusJobListener.dataChanged(JobOperationListenerManager.java:114)
at com.dangdang.ddframe.job.lite.internal.listener.AbstractJobListener.childEvent(AbstractJobListener.java:37)
at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:732)
at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:726)
at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85)
at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:725)
at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:71)
at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:843)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)

Locked ownable synchronizers:
- <0x000000008664d330> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"ENV_Online_**********************_QuartzSchedulerThread" prio=10 tid=0x00007fa38cff8000 nid=0x3f28 in Object.wait() [0x00007fa349bda000]
java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:503)
at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1342)
- locked <0x0000000584216c40> (a org.apache.zookeeper.ClientCnxn$Packet)
at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1040)
at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:226)
at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:215)
at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108)
at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForegroundStandard(ExistsBuilderImpl.java:212)
at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:205)
at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:168)
at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:39)
at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.isExisted(ZookeeperRegistryCenter.java:210)
at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.isJobRootNodeExisted(JobNodeStorage.java:109)
at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.createJobNodeIfNeeded(JobNodeStorage.java:103)
at com.dangdang.ddframe.job.lite.internal.execution.ExecutionService.setMisfire(ExecutionService.java:189)
at com.dangdang.ddframe.job.lite.internal.schedule.JobTriggerListener.triggerMisfired(JobTriggerListener.java:47)
at org.quartz.core.QuartzScheduler.notifyTriggerListenersMisfired(QuartzScheduler.java:1905)
at org.quartz.core.SchedulerSignalerImpl.notifyTriggerListenersMisfired(SchedulerSignalerImpl.java:74)
at org.quartz.simpl.RAMJobStore.applyMisfire(RAMJobStore.java:1354)
at org.quartz.simpl.RAMJobStore.acquireNextTriggers(RAMJobStore.java:1412)
- locked <0x0000000086619140> (a java.lang.Object)
at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)

Locked ownable synchronizers:
- None

**Comment by terrymanu** [comment]
请参照模板提issue，只贴个execepton我们无法重现，也不能得知版本。之前已经关闭过同样的issue了。请知晓。

**Comment by Ah39** [comment]
看清楚，这个是jstack的输出，你看过没有。真是我有时间干点啥不好，跑这里来浪费时间，呵呵呵。

**Comment by Ah39** [comment]
ps：要是能快速重现，我自己就解决了，还浪费时间在这里提issues，浪费我的时间

**Comment by terrymanu** [comment]
如果您无法把问题描述清楚，我们也无法定位问题。
开源是为了给大家提供方便，请相互理解。时间是大家的，我们查看和回复issue同样需要花费时间。

**Comment by Ah39** [comment]
那你告诉我，你好歹看了吗？？

**Comment by terrymanu** [comment]
解决issue本就是异步。我们无法保证实时对您进行支持。先期不将issue描述清楚到足够重现，我们也不会花费大量时间排查。
如果想解决issue，请提供可重现的代码。

**Comment by Ah39** [comment]
行行，你nb，以后我绕路走。这么容易可重现，我上这里来问干啥，分分钟自己解决了。

**Comment by terrymanu** [comment]
请摆正心态。我们提供开源是为了和对技术有兴趣的人共同进步。开源不是免费，而是开放，源码再次，每个人都可以开放的去学习修改和研究。
我们没有义务听取您对技术之外的抱怨。您的时间虽然宝贵，但我们的时间也不比您多任何一秒钟。
如果继续已解决这个issue为目的，欢迎继续讨论。其他目的则言尽于此。
