### ISSUE TITLE
Quartz shutdowhook job优雅关闭问题

### ISSUE THREAD

**Issue by liuhailin** [dangdangdotcom/elastic-job#394]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.5
### Expected behavior
shutdown应用的时候，能优雅关闭，不会出现异常。
### Actual behavior
不能优雅关闭，由于JobShutdownHookPlugin需要注册中心执行操作，但是注册中心Bean已经被spring容器注销
### Steps to reproduce the behavior
使用spring boot
### Please provide the reproduce example codes (such as github link) if possible.

异常信息：

Exception in thread "Quartz Shutdown-Hook com.okcoin.jobs.Example" com.dangdang.ddframe.job.reg.exception.RegException: java.lang.IllegalStateException: instance must be started before calling this method
	at com.dangdang.ddframe.job.reg.exception.RegExceptionHandler.handleException(RegExceptionHandler.java:52)
	at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:162)
	at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143)
	at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:72)
	at com.dangdang.ddframe.job.lite.internal.election.LeaderService.isLeader(LeaderService.java:84)
	at com.dangdang.ddframe.job.lite.internal.schedule.JobShutdownHookPlugin.shutdown(JobShutdownHookPlugin.java:33)
	at org.quartz.core.QuartzScheduler.shutdownPlugins(QuartzScheduler.java:2399)
	at org.quartz.core.QuartzScheduler.shutdown(QuartzScheduler.java:758)
	at org.quartz.impl.StdScheduler.shutdown(StdScheduler.java:206)
	at org.quartz.plugins.management.ShutdownHookPlugin$1.run(ShutdownHookPlugin.java:128)
Caused by: java.lang.IllegalStateException: instance must be started before calling this method
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:375)
	at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:158)
	... 8 more

**Comment by liuhailin** [comment]
`@Component
@Slf4j
public class ContainerShutDown implements DisposableBean {

    @Autowired
    private ZookeeperRegistryCenter registryCenter;

    @Override
    public void destroy() throws Exception {
        Thread.sleep(10000);
    }
}`
这样延迟销毁spring容器，可以临时解决，还有其他更好的方式吗？

**Comment by terrymanu** [comment]
这个是curator的问题，我们之前也发现了，目前没什么特别好的解决方案。
但是curator其实问题不少，因此我们也打算未来换掉它，不过暂时还没列上日程。
因此这个issue我先关了，以后换掉curaotr就可以了。

**Comment by larrychao** [comment]
我这也遇到了这个问题，采用延迟的方法已经没有用了，我给zookeeperRegCenter加了个是否close的状态，当进入close状态后，getdirectly()将直接返回null。
但curator内补还会有个类似的错误，如下，无法解决
2018-08-16 14:07:41,665 11233 ERROR   o.a.c.f.recipes.cache.TreeCache(751) - 
java.lang.IllegalStateException: instance must be started before calling this method
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getChildren(CuratorFrameworkImpl.java:391)
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.doRefreshChildren(TreeCache.java:263)
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.refreshChildren(TreeCache.java:251)
	at org.apache.curator.framework.recipes.cache.TreeCache$TreeNode.process(TreeCache.java:351)
	at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:62)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)

**Comment by fhyfhy17** [comment]
> ```
> @Component
> public class ContainerShutDown implements DisposableBean {
> 
>     @Autowired
>     private ZookeeperRegistryCenter registryCenter;
> 
>     @Override
>     public void destroy() throws Exception {
>         Thread.sleep(10000);
>     }
> }
> ```
> 
> 这样延迟销毁spring容器，可以临时解决，还有其他更好的方式吗？

自己试了下  @Predestroy 和  监听 ContextCloseEvent ， 后面一种执行的最早，应该是在对象销毁之前吧。
![image](https://user-images.githubusercontent.com/7513465/65130507-2117bd00-da30-11e9-9200-8d3d2bcd3006.png)

**Comment by jpfss** [comment]
利用" @Predestroy"注解来让在销毁前睡两秒也可以暂时解决 @&@
