### ISSUE TITLE
mesos平台上注册了Elastic-Job-Cloud framework后，其它的framework比如jenkins scheduler，marathon等都不能执行任务了

### ISSUE THREAD

**Issue by william-xu2003** [dangdangdotcom/elastic-job#396]
使用的Elastic-Job-Cloud版本是2.1.5，使用的mesos版本1.3.0

mesos平台上注册了Elastic-Job-Cloud framework后，其它的framework比如jenkins scheduler，marathon等都不能执行任务了，在mesos控制台上的offers里面有很多该framework的Outstanding Offers。一旦注销该framework后，其它的framework马上能分配任务执行。

**Comment by terrymanu** [comment]
elastic-job-cloud依赖的mesos版本：<mesos.version>1.1.0</mesos.version>

我们内部是与marathon一起用的，没有任何问题

**Comment by candyYu** [comment]
mesos平台上如何注册上Elastic-Job-Cloud framework呀？我启动了elasticjob-cloud-scheduler好像不行，执行作业时候报错：
[ERROR] 2021-02-20 15:40:16,669 --task-launch-processor RUNNING-- [org.apache.shardingsphere.elasticjob.cloud.scheduler.mesos.TaskLaunchScheduledService] Launch task error
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
	at org.apache.shardingsphere.elasticjob.cloud.scheduler.mesos.MesosStateService.fetch(MesosStateService.java:134)
	at org.apache.shardingsphere.elasticjob.cloud.scheduler.mesos.MesosStateService.executors(MesosStateService.java:114)
	at org.apache.shardingsphere.elasticjob.cloud.scheduler.mesos.MesosStateService.executors(MesosStateService.java:130)
	at org.apache.shardingsphere.elasticjob.cloud.scheduler.mesos.FacadeService.loadExecutorInfo(FacadeService.java:327)
	at org.apache.shardingsphere.elasticjob.cloud.scheduler.mesos.AppConstraintEvaluator.loadAppRunningState(AppConstraintEvaluator.java:70)
	at org.apache.shardingsphere.elasticjob.cloud.scheduler.mesos.TaskLaunchScheduledService.runOneIteration(TaskLaunchScheduledService.java:105)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:221)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
