### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by hoswey** [dangdangdotcom/elastic-job#401]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.5

配置了event-trace-rdb-data-source，自动创建的索引的长度超出mysql的默认索引长度

Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [na:1.8.0_65]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:989) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.createTaskIdAndStateIndex(JobEventRdbStorage.java:147) ~[elastic-job-common-core-2.1.5.jar:na]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.createTaskIdIndexIfNeeded(JobEventRdbStorage.java:101) ~[elastic-job-common-core-2.1.5.jar:na]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.createJobStatusTraceTableAndIndexIfNeeded(JobEventRdbStorage.java:88) ~[elastic-job-common-core-2.1.5.jar:na]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.initTablesAndIndexes(JobEventRdbStorage.java:67) ~[elastic-job-common-core-2.1.5.jar:na]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.<init>(JobEventRdbStorage.java:61) ~[elastic-job-common-core-2.1.5.jar:na]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbListener.<init>(JobEventRdbListener.java:37) ~[elastic-job-common-core-2.1.5.jar:na]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbConfiguration.createJobEventListener(JobEventRdbConfiguration.java:46) ~[elastic-job-common-core-2.1.5.jar:na]
	... 25 common frames omitted

**Comment by terrymanu** [comment]
mysql字符集设置问题。
请自行google并配置自己本地的数据库
