### ISSUE TITLE
Regarding mysql param - lower_case_table_names=1, can we change JobEventRdbStorage to identify index igoreCase? 

### ISSUE THREAD

**Issue by pink-lucifer** [dangdangdotcom/elastic-job#404]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.5
### Actual behavior
JobEventRdbStorage.java method createTaskIdIndexIfNeeded:
indexName.equals(resultSet.getString("INDEX_NAME")) 
to be 
indexName.equalsIgnoreCase(resultSet.getString("INDEX_NAME"))
### Steps to reproduce the behavior
Mysql 5.6 database, my.cnf  hava 
 **lower_case_table_names=1**

pre-create the table,  ... start the application ---  below exception is gonng be hit:
2017-09-11 15:33:24.660 ERROR 12148 --- [           main] druid.sql.Statement                      : {conn-10005, pstmt-20000} execute error. CREATE INDEX TASK_ID_STATE_INDEX ON JOB_STATUS_TRACE_LOG (`task_id`, `state`);

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate key name 'TASK_ID_STATE_INDEX'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2494)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3051)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3049)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3049)
	at com.alibaba.druid.wall.WallFilter.preparedStatement_execute(WallFilter.java:601)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3049)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:168)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:494)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.createTaskIdAndStateIndex(JobEventRdbStorage.java:147)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.createTaskIdIndexIfNeeded(JobEventRdbStorage.java:101)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.createJobStatusTraceTableAndIndexIfNeeded(JobEventRdbStorage.java:88)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.initTablesAndIndexes(JobEventRdbStorage.java:67)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.<init>(JobEventRdbStorage.java:61)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbListener.<init>(JobEventRdbListener.java:37)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbConfiguration.createJobEventListener(JobEventRdbConfiguration.java:46)
	at com.dangdang.ddframe.job.event.JobEventBus.register(JobEventBus.java:57)
	at com.dangdang.ddframe.job.event.JobEventBus.<init>(JobEventBus.java:52)
	at com.dangdang.ddframe.job.lite.api.JobScheduler.<init>(JobScheduler.java:79)
	at com.dangdang.ddframe.job.lite.spring.api.SpringJobScheduler.<init>(SpringJobScheduler.java:46)
	at com.ebyf.wm.ftc.batch.config.SimpleJobConfig.portfolioValuationSimpleJobScheduler(SimpleJobConfig.java:43)
	at com.ebyf.wm.ftc.batch.config.SimpleJobConfig$$EnhancerBySpringCGLIB$$e03b4ff9.CGLIB$portfolioValuationSimpleJobScheduler$3(<generated>)
	at com.ebyf.wm.ftc.batch.config.SimpleJobConfig$$EnhancerBySpringCGLIB$$e03b4ff9$$FastClassBySpringCGLIB$$9ac67989.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at com.ebyf.wm.ftc.batch.config.SimpleJobConfig$$EnhancerBySpringCGLIB$$e03b4ff9.portfolioValuationSimpleJobScheduler(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.ebyf.wm.ftc.batch.FtcBatchApplication.main(FtcBatchApplication.java:12)
### Please provide the reproduce example codes (such as github link) if possible.
https://github.com/pink-lucifer/elastic-job-demo.git

notes: this seems only happen if we use lower case script to create table & indexes.

**Comment by terrymanu** [comment]
https://www.oschina.net/question/2267663_2266049
请知悉，我们不会将重点放在这里

**Comment by pink-lucifer** [comment]
好的，
