### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/jute/CsvOutputArchive

### ISSUE THREAD

**Issue by lanmo** [dangdangdotcom/elastic-job#430]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
version:2.1.5
### Expected behavior
java.lang.NoClassDefFoundError: org/apache/jute/CsvOutputArchive
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at org.apache.zookeeper.ClientCnxn$Packet.toString(ClientCnxn.java:313)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:818)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:94)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1343)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1206)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
        ... 10 more
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1353)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1341)
        ... 12 more
java.lang.NoClassDefFoundError: org/apache/jute/CsvOutputArchive
        at org.apache.zookeeper.proto.SetDataResponse.toString(SetDataResponse.java:52)
        at org.apache.zookeeper.ClientCnxn$Packet.toString(ClientCnxn.java:314)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:818)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:94)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1343)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1206)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
        ... 10 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.jute.CsvOutputArchive]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1353)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1341)
        ... 12 more
Exception in thread "Quartz Shutdown-Hook dispatcherStatus" java.lang.NoClassDefFoundError: org/apache/curator/framework/imps/DeleteBuilderImpl$5
        at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:235)
        at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:218)
        at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:42)
        at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.remove(ZookeeperRegistryCenter.java:280)
        at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.removeJobNodeIfExisted(JobNodeStorage.java:119)
        at com.dangdang.ddframe.job.lite.internal.election.LeaderService.removeLeader(LeaderService.java:100)
        at com.dangdang.ddframe.job.lite.internal.schedule.JobShutdownHookPlugin.shutdown(JobShutdownHookPlugin.java:34)
        at org.quartz.core.QuartzScheduler.shutdownPlugins(QuartzScheduler.java:2399)
        at org.quartz.core.QuartzScheduler.shutdown(QuartzScheduler.java:758)
        at org.quartz.impl.StdScheduler.shutdown(StdScheduler.java:206)
        at org.quartz.plugins.management.ShutdownHookPlugin$1.run(ShutdownHookPlugin.java:128)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.curator.framework.imps.DeleteBuilderImpl$5]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1343)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1206)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
        ... 11 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.curator.framework.imps.DeleteBuilderImpl$5]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1353)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1341)
        ... 13 more
### Actual behavior
项目中没有单独引用zk，和curator，所有的依赖都是elastic-job-lite-core间接依赖的

**Comment by terrymanu** [comment]
请先自行将example跑一下吧。
这种第三方依赖和elastic job没关系的。
